name: CI CD

on:
  push:
    branches: [ main, feature/add-pipeline ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PUBLISH_FOLDER: './publish'
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      
      - name: Install .NET 6 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Publish
        run: |
          dotnet publish 'Bicep.Fiddle.BlazorApp/Bicep.Fiddle.BlazorApp.csproj'\
            --output ${{ env.PUBLISH_FOLDER }}\
            --framework net6.0\
            --runtime linux-x64\
            --configuration release\
            --self-contained
            
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
