name: CI CD

on:
  push:
    branches: [ main, feature/add-pipeline ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PUBLISH_FOLDER: './publish'
      AZURE_RESOURCE_GROUP_NAME: 'bicepfiddle-rg' 
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      
      - name: Install .NET 6 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Publish
        run: |
          dotnet publish 'Bicep.Fiddle.BlazorApp/Bicep.Fiddle.BlazorApp.csproj'\
            --output ${{ env.PUBLISH_FOLDER }}\
            --framework net6.0\
            --runtime linux-x64\
            --configuration release\
            --self-contained
            
      - name: Azure Login 🔑
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Ensure Azure Resource Group Created
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az group create --location australiaeast --name ${{ env.AZURE_RESOURCE_GROUP_NAME }}
      
      - name: Update Azure Resource Group 💪
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create\
              --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }}\
              --template-file 'Bicep.Fiddle.Infrastructure/azure/resource-group.bicep'\
              --name ${{ github.run_number }}
        
      - name: Set WebAppName Env Variable
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            echo "WEBAPP_NAME=$(az deployment group show\
              --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }}\
              --name ${{ github.run_number }}\
              --query properties.outputs.webAppName.value)" >> $GITHUB_ENV

      - name: Deploy Blazor App 🚀
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: ${{ env.PUBLISH_FOLDER }}
