name: CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PUBLISH_FOLDER: './publish'
      AZURE_RESOURCE_GROUP_NAME: 'rg-bicepfiddle-development'
      ASPNETCORE_ENVIRONMENT: 'Development'
      APPSERVICEPLAN_NAME: 'plan-bicepfiddle-development'
      WEBAPP_NAME: 'app-bicepfiddle-development'
      KEYVAULT_NAME: 'kv-bicepfiddle-dev'
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      
      - name: Install .NET 6 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Publish Blazor App
        run: |
          dotnet publish 'Bicep.Fiddle.BlazorApp/Bicep.Fiddle.BlazorApp.csproj'\
            --output ${{ env.PUBLISH_FOLDER }}\
            --framework net6.0\
            --runtime linux-x64\
            --configuration release\
            --self-contained
            
      - name: Azure Login 🔑
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Ensure Azure Resource Group Created
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az group create --location australiaeast --name ${{ env.AZURE_RESOURCE_GROUP_NAME }}
      
      - name: Update Azure Resource Group 💪
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create\
              --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }}\
              --name ${{ github.run_number }}\
              --template-file 'Bicep.Fiddle.Infrastructure/azure/resource-group.bicep'\
              --parameters aspnetcore_environment=${{ env.ASPNETCORE_ENVIRONMENT }}\
              --parameters appServicePlanName=${{ env.APPSERVICEPLAN_NAME }}\
              --parameters webAppName=${{ env.WEBAPP_NAME }}\
              --parameters keyVaultName=${{ env.KEYVAULT_NAME }}
        
      - name: Deploy Blazor App 🚀
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: ${{ env.PUBLISH_FOLDER }}