name: CI CD

on:
  push:
    branches: [ main, feature/add-pipeline ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PUBLISH_FOLDER: './publish'
      AZURE_RESOURCE_GROUP_NAME: 'bicepfiddle-rg' 
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      
      - name: Install .NET 6 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Publish
        run: |
          dotnet publish 'Bicep.Fiddle.BlazorApp/Bicep.Fiddle.BlazorApp.csproj'\
            --output ${{ env.PUBLISH_FOLDER }}\
            --framework net6.0\
            --runtime linux-x64\
            --configuration release\
            --self-contained
            
      - name: Azure Login 🔑
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Ensure Azure Resource Group Created
      #   uses: Azure/cli@1.0.4
      #   with:
      #     inlineScript: az group create --location australiaeast --name ${{ env.AZURE_RESOURCE_GROUP_NAME }}
      
      - uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.AZURE_RESOURCE_GROUP_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.AZURE_RESOURCE_GROUP_NAME }} --location australiaeast
              echo "Azure resource group created"
            fi

      - name: Update Azure Resource Group 💪
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create\
              --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }}\
              --template-file 'Bicep.Fiddle.Infrastructure/azure/resource-group.bicep'