name: CI CD

on:
  push:
    branches: [ main, feature/add-pipeline ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: dotnet build Bicep.Fiddle.BlazorApp/Bicep.Fiddle.BlazorApp.csproj
